version: 2.1

orbs:
  node: circleci/node@4.1.0

nightly:
  triggers:
        - cron: "12 18 * * *"
        - cron: "0 20 * * *"
jobs:

  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Giving permissions
          command: chmod +x mvnw
      - run:   
          command: ./mvnw -Dmaven.test.skip=true package









